#!/usr/bin/env python3
"""
Generate .include delta files that give the AI a sandbox-only +1 weight for
advisor roles whose vanilla ai_will_do sits at an unconditional zero.

For each vanilla common/characters/*.txt, every `advisor` block whose direct
`ai_will_do` child has top-level `base = 0` (0, 0.0, 0.000) is targeted,
EXCEPT blocks where a direct-child `modifier` already carries an `add`:
those hire conditionally by authorial design (e.g. monarchist-only advisors)
and must keep their gate. `factor`-only zero blocks are out of scope.

Each target gets, via its `characters -> <id> -> [instance] -> advisor` path:

    +modifier:
      add(1)
      is_sandbox_mode_on()

which the HSL compiler turns into:

    modifier = {
        add = 1
        is_sandbox_mode_on = yes
    }

Files without targets produce no .include (mirror convention: one .include
per vanilla file, same basename).

Usage:
    python enable_ai_for_advisors.py [in_dir] [out_dir]

Defaults (this machine's layout; override via argv):
    in_dir  = vanilla common/characters
    out_dir = _sandbox common/characters
"""

import os
import pathlib
import re
import sys

from disable_ai_for_ideas import (
    _iter_named_blocks,
    _has_direct_child,
    repair_eof_braces,
    diagnose_brace_balance,
    _WORD_CHARS,
    _is_word_char,
    _skip_comment,
    _skip_string,
)

VANILLA_CHARACTERS = (
    r"C:\Games\Steam\steamapps\common\Hearts of Iron IV\common\characters"
)
MOD_CHARACTERS = (
    r"C:\Users\evgeny\Documents\Paradox Interactive\Hearts of Iron IV"
    r"\mod\_sandbox\common\characters"
)

INDENT = "  "  # two spaces per level, matching the project's HSL rendering

_ZERO_BASE = re.compile(r"^0(\.0+)?$")

# The modifier body injected into each targeted ai_will_do block.
_MODIFIER_LINES = [
    "+modifier:",
    "  add(1)",
    "  is_sandbox_mode_on()",
]

def _header_block(in_dir):
    script = str(pathlib.Path(__file__).resolve())
    return "\n".join([
        f"# Generated by {script} from:",
        f"#   {in_dir}",
        "# Sandbox-only +1 AI weight for advisor roles whose ai_will_do sits",
        "# at base 0 with no conditional add. Do not edit by hand; rerun it.",
    ])


def _direct_scalars(text, start, end):
    """Dict of direct-child `key = value` scalars (non-brace) in text[start:end]."""
    out = {}
    i, depth = start, 0
    while i < end:
        c = text[i]
        if c == '#':
            i = _skip_comment(text, i)
            continue
        if c == '"':
            i = _skip_string(text, i)
            continue
        if c == '{':
            depth += 1
            i += 1
            continue
        if c == '}':
            depth -= 1
            i += 1
            continue
        if depth == 0 and c in _WORD_CHARS and not _is_word_char(text, i - 1):
            j = i
            while j < end and text[j] in _WORD_CHARS:
                j += 1
            key = text[i:j]
            k = j
            while k < end and text[k] in ' \t\r\n':
                k += 1
            if k < end and text[k] == '=':
                k += 1
                while k < end and text[k] in ' \t\r\n':
                    k += 1
                if k < end and text[k] != '{':
                    e = k
                    while e < end and text[e] != '\n':
                        e += 1
                    val = text[k:e].strip().strip('"')
                    out.setdefault(key, val)
                    i = e
                    continue
            i = j
            continue
        i += 1
    return out


def _modifier_has_add(text, start, end):
    """True when any direct-child `modifier` block has a direct `add` scalar."""
    for name, mo, mc in _iter_named_blocks(text, start, end):
        if name != "modifier":
            continue
        if "add" in _direct_scalars(text, mo, mc):
            return True
    return False


def _eval_ai_will_do(text, start, end):
    """'target' | 'conditional' | 'ignore' for one ai_will_do body."""
    scalars = _direct_scalars(text, start, end)
    base = scalars.get("base")
    if base is None or not _ZERO_BASE.fullmatch(base.strip()):
        return "ignore"
    if _modifier_has_add(text, start, end):
        return "conditional"
    return "target"


def _walk(text, start, end, path, targets, skipped):
    """Collect advisor-owned ai_will_do targets under path (list of segments).

    Each segment is (name, index|None); index is the 0-based position among
    same-named siblings, or None when the name is unique (bare header then
    resolves to the intended block)."""
    children = list(_iter_named_blocks(text, start, end))
    counts = {}
    for name, _, _ in children:
        counts[name] = counts.get(name, 0) + 1
    seen = {}
    for name, o, c in children:
        pos = seen.get(name, 0)
        seen[name] = pos + 1
        seg = (name, pos if counts[name] > 1 else None)
        if name == "advisor":
            ai_blocks = [(ao, ac) for an, ao, ac
                         in _iter_named_blocks(text, o, c) if an == "ai_will_do"]
            # _iter_named_blocks yields in order; index repeats if duplicated.
            ai_seen = 0
            for ao, ac in ai_blocks:
                ai_idx = ai_seen
                ai_seen += 1
                ai_seg = ("ai_will_do", ai_idx if len(ai_blocks) > 1 else None)
                verdict = _eval_ai_will_do(text, ao, ac)
                if verdict == "target":
                    targets.append(path + [seg, ai_seg])
                elif verdict == "conditional":
                    skipped.append(path + [seg, ai_seg])
        _walk(text, o, c, path + [seg], targets, skipped)


def find_targets(text):
    """All (target_paths, skipped_paths) in one characters file."""
    targets, skipped = [], []
    top = list(_iter_named_blocks(text, 0, len(text)))
    counts = {}
    for name, _, _ in top:
        counts[name] = counts.get(name, 0) + 1
    seen = {}
    for name, o, c in top:
        if name != "characters":
            continue
        pos = seen.get(name, 0)
        seen[name] = pos + 1
        seg = (name, pos if counts[name] > 1 else None)
        _walk(text, o, c, [seg], targets, skipped)
    return targets, skipped


def _header(name, index):
    return f"{name}[{index}]" if index is not None else name


def _leaf_id(path):
    """Short label for a target path: the character id segment."""
    for name, _ in path[1:]:
        if name not in ("instance", "advisor", "ai_will_do", "characters"):
            return name
    return path[1][0] if len(path) > 1 else "?"


def build_include(targets, in_dir):
    """Render the .include source, grouping targets under their shared
    character header (first-seen order). A `[N]` selector is emitted for any
    name that repeats among its siblings."""
    lines = [_header_block(in_dir), "characters:"]

    grouped = {}
    order = []
    for path in targets:
        key = path[1]
        if key not in grouped:
            grouped[key] = []
            order.append(key)
        grouped[key].append(path)

    for n, key in enumerate(order):
        if n > 0:
            # Blank line between character blocks (not before the first).
            lines.append("")
        depth = 1
        for name, index in [key]:
            lines.append(f"{INDENT * depth}{_header(name, index)}:")
            depth += 1
        for path in grouped[key]:
            for name, index in path[2:]:
                lines.append(f"{INDENT * depth}{_header(name, index)}:")
                depth += 1
            for ml in _MODIFIER_LINES:
                lines.append(f"{INDENT * depth}{ml}")
            depth = 2
    return "\n".join(lines) + "\n"


def process_dir(in_dir, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    written = skipped_files = errored = repaired = 0
    total_targets = total_skipped = 0
    for fname in sorted(os.listdir(in_dir)):
        if not fname.endswith(".txt"):
            continue
        in_path = os.path.join(in_dir, fname)
        if not os.path.isfile(in_path):
            continue
        with open(in_path, "r", encoding="utf-8-sig") as f:
            text = f.read()
        text, n_added = repair_eof_braces(text)
        if n_added:
            repaired += 1
        try:
            targets, skipped = find_targets(text)
        except ValueError as e:
            hint = diagnose_brace_balance(text)
            print(f"  !! {fname}: skipped ({hint if hint else e})")
            errored += 1
            continue
        skip_ids = sorted({_leaf_id(p) for p in skipped})
        total_skipped += len(skipped)
        if not targets:
            skipped_files += 1
            extra = f" (all {len(skipped)} conditional: {', '.join(skip_ids)})" if skipped else ""
            print(f"  {fname}: no targets{extra}")
            continue
        out_name = fname[:-len(".txt")] + ".include"
        out_text = build_include(targets, in_dir)
        # A hand-maintained `<stem>.extra` beside the output is appended verbatim,
        # so manual patches to a generated include survive regeneration.
        extra_path = os.path.join(out_dir, fname[:-len(".txt")] + ".extra")
        if os.path.isfile(extra_path):
            with open(extra_path, "r", encoding="utf-8-sig") as ef:
                extra_text = ef.read().rstrip("\n")
            out_text = out_text.rstrip("\n") + "\n\n" + extra_text + "\n"
        with open(os.path.join(out_dir, out_name), "w", encoding="utf-8") as f:
            f.write(out_text)
        total_targets += len(targets)
        extra = f"; skipped conditional: {', '.join(skip_ids)}" if skip_ids else ""
        print(f"  {fname}: {len(targets)} target(s) -> {out_name}{extra}")
        written += 1
    print(f"Done. {written} include file(s) written ({total_targets} targets), "
          f"{skipped_files} file(s) without targets ({total_skipped} conditional skips), "
          f"{repaired} auto-closed, {errored} parse errors.")


def main():
    in_dir = sys.argv[1] if len(sys.argv) > 1 else VANILLA_CHARACTERS
    out_dir = sys.argv[2] if len(sys.argv) > 2 else MOD_CHARACTERS
    if not os.path.isdir(in_dir):
        print(f"Input directory not found: {in_dir}")
        sys.exit(1)
    process_dir(in_dir, out_dir)


if __name__ == "__main__":
    main()
